reference:
    HIS: 2.15 # Average cysteines values between ZF1-ZF2 Qm calculations
    CYS: 2.38 # Average histidine values between ZF1-ZF2 Qm calculations

out_name1: FigureS1.pdf
out_name2: Npl4_129-151_Zn_compare_distance_400_500K.pdf

md:
    ZF1:
        charmm36:
            his139:
                rep1:
                    replicate1/charmm36/NH2_CT2/md/ZN2_H139.xvg
                rep2:
                    replicate2/charmm36/NH2_CT2/md/ZN2_H139.xvg
                rep3:
                    replicate3/charmm36/NH2_CT2/md/ZN2_H139.xvg
                NH2-CT3:
                    replicate1/charmm36/NH2_CT3/md/ZN2_H139.xvg
            cys137:
                rep1:
                    replicate1/charmm36/NH2_CT2/md/ZN2_C137.xvg
                rep2:
                    replicate2/charmm36/NH2_CT2/md/ZN2_C137.xvg
                rep3:
                    replicate3/charmm36/NH2_CT2/md/ZN2_C137.xvg
                NH2-CT3:
                    replicate1/charmm36/NH2_CT3/md/ZN2_C137.xvg
            cys145:
                rep1:
                    replicate1/charmm36/NH2_CT2/md/ZN2_C145.xvg
                rep2:
                    replicate2/charmm36/NH2_CT2/md/ZN2_C145.xvg
                rep3:
                    replicate3/charmm36/NH2_CT2/md/ZN2_C145.xvg
                NH2-CT3:
                    replicate1/charmm36/NH2_CT3/md/ZN2_C145.xvg
            cys148:
                rep1:
                    replicate1/charmm36/NH2_CT2/md/ZN2_C148.xvg
                rep2:
                    replicate2/charmm36/NH2_CT2/md/ZN2_C148.xvg
                rep3:
                    replicate3/charmm36/NH2_CT2/md/ZN2_C148.xvg
                NH2-CT3:
                    replicate1/charmm36/NH2_CT3/md/ZN2_C148.xvg
        ff99SB-ILDN:
            his139:
                rep1:
                    replicate1/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
                rep2:
                    replicate2/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
                rep3:
                    replicate3/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
            cys137:
                rep1:
                    replicate1/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
                rep2:
                    replicate2/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
                rep3:
                    replicate3/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
            cys145:
                rep1:
                    replicate1/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
                rep2:
                    replicate2/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
                rep3:
                    replicate3/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
            cys148:
                rep1:
                    replicate1/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg
                rep2:
                    replicate2/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg
                rep3:
                    replicate3/ff99SB-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg

        ff99SBstar-ILDN:
            his139:
                rep1:
                    replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
                rep2:
                    replicate2/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
                rep3:
                    replicate3/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_H139.xvg
            cys137:
                rep1:
                    replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
                rep2:
                    replicate2/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
                rep3:
                    replicate3/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C137.xvg
            cys145:
                rrep1:
                    replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
                rep2:
                    replicate2/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
                rep3:
                    replicate3/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C145.xvg
            cys148:
                rep1:
                    replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg
                rep2:
                    replicate2/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg
                rep3:
                    replicate3/ff99SBstar-ILDN/ACE_NH2_terminals/md/ZN2_C148.xvg


md_highT:
    his139:
        ff99SB-ILDN-400K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_400/ZN2_H139.xvg
        ff99SBstar-ILDN-400K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_400/ZN2_H139.xvg
        ff99SB-ILDN-500K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_500/ZN2_H139.xvg
        ff99SBstar-ILDN-500K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_500/ZN2_H139.xvg
    cys137:
        ff99SB-ILDN-400K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_400/ZN2_C137.xvg
        ff99SBstar-ILDN-400K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_400/ZN2_C137.xvg
        ff99SB-ILDN-500K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_500/ZN2_C137.xvg
        ff99SBstar-ILDN-500K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_500/ZN2_C137.xvg
    cys145:
        ff99SB-ILDN-400K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_400/ZN2_C145.xvg
        ff99SBstar-ILDN-400K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_400/ZN2_C145.xvg
        ff99SB-ILDN-500K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_500/ZN2_C145.xvg
        ff99SBstar-ILDN-500K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_500/ZN2_C145.xvg
    cys148:
        ff99SB-ILDN-400K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_400/ZN2_C148.xvg
        ff99SBstar-ILDN-400K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_400/ZN2_C148.xvg
        ff99SB-ILDN-500K:
            replicate1/ff99SB-ILDN/ACE_NH2_terminals/md_500/ZN2_C148.xvg
        ff99SBstar-ILDN-500K:
            replicate1/ff99SBstar-ILDN/ACE_NH2_terminals/md_500/ZN2_C148.xvg
